### ISSUE TITLE
把代码贴上来看看

### ISSUE THREAD

**Issue by Organ1sm** [bajdcc/clibalgserver#2]
把代码贴上来看看

_Originally posted by @bajdcc in https://github.com/bajdcc/clibalgserver/issues/1#issuecomment-591738053_

**Comment by Organ1sm** [comment]
代码一开始我是直接拉下来，按照你的步骤32位编译，然后编译一切正常。上了本地服务器的算法可视化页面，运行上面的测试一维数组，二维数组等等测试都是没有问题的。
而一旦涉及到下面的算法，就running timeout .然后我debug跟踪到那个条件判断。就是下面代码的位置，这段代码在parser.cpp。
```cpp
if (output.empty()) {
            output = "{\"code\":400,\"error\":\"empty tracer\"}";
}
else if (run) {
            output = "{\"code\":400,\"error\":\"running timeout\"}";
}
``` 
然后我查看变量情况，一旦我执行到这，无论代码的编译结果如何都直接进入下面这个分支。我把run取反，算法可视化的确能够返回结果，但是可视化运行过程中，直到可视化运行结束，结果都是不正确的。比如排序算法，最后得出排序结果并没有完全排完。
![TN)$5I{_``DKLX~@KDE09E](https://user-images.githubusercontent.com/49949944/75405955-2287d280-594a-11ea-9ee3-5d120de001a4.png)

**Comment by bajdcc** [comment]
在你贴的代码上面第40行有2s超时，改一下。

**Comment by Organ1sm** [comment]
已改，结果正确。我想按照这个工程的思路想法，去试试算法可视化这个思路，去实现它。如果你方便的话，可以给个邮箱或者啥的吗？或者其他平台私信也好。我之前在知乎上一直关注你，给你发私信，但是观察你更新的文章频率考虑到你平常可能不怎么上知乎，所以我就上github提issue,谢谢你的帮助。

**Comment by bajdcc** [comment]
私信发个wx或qq也可。

**Comment by Organ1sm** [comment]
那我直接知乎私信wx给你。
