### ISSUE TITLE
你好，请问项目是怎么部署的呢

### ISSUE THREAD

**Issue by mokeeqian** [bajdcc/clibalgserver#3]
如题，项目如何部署

**Comment by bajdcc** [comment]
看readme中有代码打包下载可以直接用，编译的话用vs2019打开项目，然后win32编译，运行编译好的exe，再打开网页http://localhost:8080
网页打开后左边有示例代码

**Comment by mokeeqian** [comment]
好的，谢谢，已经部署好了，学习学习
